
package main;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.apache.cxf.frontend.ClientProxy;
import java.util.HashMap;
import java.util.Map;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.wss4j.dom.handler.WSHandlerConstants;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-28T13:06:17.195+01:00
 * Generated source version: 3.5.11
 *
 */
public final class BankService_BankServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://main/", "BankServiceImplService");

    private BankService_BankServiceImplPort_Client() {}

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankServiceImplService.WSDL_LOCATION;
        
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BankServiceImplService ss = new BankServiceImplService(wsdlURL, SERVICE_NAME);
        BankService port = ss.getBankServiceImplPort();

        // security interceptor
        Client client = ClientProxy.getClient(port);

        Map<String, Object> props = new HashMap<>();
        props.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);
        props.put(WSHandlerConstants.USER, "username");
        props.put(WSHandlerConstants.PASSWORD_TYPE, "PasswordText");
        props.put(WSHandlerConstants.PW_CALLBACK_CLASS, ClientPasswordCallback.class.getName());

        WSS4JOutInterceptor wssOut = new WSS4JOutInterceptor(props);
        client.getOutInterceptors().add(wssOut);
        
        {
	        System.out.println("Invoking getBalance...");
	        double _getBalance__return = port.getBalance();
	        System.out.println("getBalance.result=" + _getBalance__return);
        }

        System.exit(0);
    }

}
