
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package main;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-28T13:06:17.223+01:00
 * Generated source version: 3.5.11
 *
 */

@javax.jws.WebService(
                      serviceName = "BankServiceImplService",
                      portName = "BankServiceImplPort",
                      targetNamespace = "http://main/",
                      wsdlLocation = "file:/Users/tomasboda/Documents/Development/eclipse/05-cxf/src/main/webapp/wsdl/bankserviceimpl.wsdl",
                      endpointInterface = "main.BankService")

public class BankServiceImplPortImpl implements BankService {

    private static final Logger LOG = Logger.getLogger(BankServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see main.BankService#getBalance()*
     */
    public double getBalance() {
        LOG.info("Executing operation getBalance");
        try {
            double _return = 0.5918418812345411;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
