
package main.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.11
 * Thu Mar 27 21:29:08 CET 2025
 * Generated source version: 3.5.11
 */

@XmlRootElement(name = "getBalance", namespace = "http://main/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBalance", namespace = "http://main/")

public class GetBalance {


}

