
package main;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-28T13:06:17.195+01:00
 * Generated source version: 3.5.11
 *
 */
public final class BankService_BankServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://main/", "BankServiceImplService");

    private BankService_BankServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BankServiceImplService ss = new BankServiceImplService(wsdlURL, SERVICE_NAME);
        BankService port = ss.getBankServiceImplPort();

        {
        System.out.println("Invoking getBalance...");
        double _getBalance__return = port.getBalance();
        System.out.println("getBalance.result=" + _getBalance__return);


        }

        System.exit(0);
    }

}
