package main;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-28T13:06:17.239+01:00
 * Generated source version: 3.5.11
 *
 */
@WebServiceClient(name = "BankServiceImplService",
                  wsdlLocation = "file:/Users/tomasboda/Documents/Development/eclipse/05-cxf/src/main/webapp/wsdl/bankserviceimpl.wsdl",
                  targetNamespace = "http://main/")
public class BankServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://main/", "BankServiceImplService");
    public static final QName BankServiceImplPort = new QName("http://main/", "BankServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/tomasboda/Documents/Development/eclipse/05-cxf/src/main/webapp/wsdl/bankserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/tomasboda/Documents/Development/eclipse/05-cxf/src/main/webapp/wsdl/bankserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BankServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public BankService getBankServiceImplPort() {
        return super.getPort(BankServiceImplPort, BankService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public BankService getBankServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BankServiceImplPort, BankService.class, features);
    }

}
