package main;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-28T13:06:17.236+01:00
 * Generated source version: 3.5.11
 *
 */
@WebService(targetNamespace = "http://main/", name = "BankService")
@XmlSeeAlso({ObjectFactory.class})
public interface BankService {

    @WebMethod(action = "urn:GetBalance")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://main/", className = "main.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://main/", className = "main.GetBalanceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double getBalance()
;
}
